version: '3.7'

services:
  vs-code-server:
    build:
      context: ./VS_CODE_DEV_SERVER
      dockerfile: Dockerfile
    volumes:
      # project's location
      - ./:/home/coder/project
      # setting's location
      - ./.vscode-config:/root/.local/share/code-server/User
    container_name: vs-code-server
    environment:
      - PASSWORD=1234 #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=1234 #optional
      #- SUDO_PASSWORD_HASH= #optional
      - http_proxy=127.0.0.1:5555
    ports:
      - 8090:8080
      - 5555:5555
