version: '3.7'

services:
  spring-boot-reloader:
    build:
      context: ./Tiramisu_Spring_Boot
      dockerfile: Dockerfile
    volumes:
      - ./Tiramisu_Spring_Boot:/tmp
    working_dir: /tmp
    container_name: spring-boot-reloader
    command: [ "bash", "./buildAndReload.sh" ]

  spring-boot:
    build:
      context: ./Tiramisu_Spring_Boot
      dockerfile: Dockerfile
    volumes:
      - ./Tiramisu_Spring_Boot:/tmp
    working_dir: /tmp
    container_name: spring-boot
    command: [ "bash", "./bootRun.sh" ]
    ports:
      - 64510:8080
      - 35729:35729
      - 5005:5005

  hapi-fhir:
    image: "hapiproject/hapi:latest"
    volumes:
      - ./HAPI-FHIR:/data/hapi
    container_name: hapi-fhir
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
    ports:
      - 64511:8080

  vs-code-server:
    build:
      context: ./VS_CODE_DEV_SERVER
      dockerfile: Dockerfile
    volumes:
      # project's location
      - ./:/home/coder/project
      # setting's location
      - ./.vscode-config:/root/.local/share/code-server/User
      # gradle dependency location
      - ./VS_CODE_DEV_SERVER/gradle_dependency:/root/.gradle/caches/modules-2/files-2.1
    container_name: vs-code-server
    environment:
      - PASSWORD=1234 #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=1234 #optional
      #- SUDO_PASSWORD_HASH= #optional
    ports:
      - 64550:8080

  Hardhat:
    build:
      context: ./Hardhat
      dockerfile: Dockerfile
    volumes:
      -./Hardhat:/tmp
    working_dir: /tmp
    container_name: hardhat

  Angular-server:
    build:
      dockerfile: Dockerfile
    container_name: angular-server
    ports:
      - 64500:8080
