version: '3.7'

services:
  spring-boot-reloader:
    image: gradle:latest
    volumes:
      - ./Spring-Boot:/tmp/Spring-Boot
      - /gradle_dependency:/root/.gradle/caches/modules-2/files-2.1
    working_dir: /tmp/Spring-Boot
    container_name: spring-boot-reloader
    command: [ "bash", "./buildAndReload.sh" ]

  spring-boot:
    image: gradle:latest
    volumes:
      - ./Spring-Boot:/tmp/Spring-Boot
      - /gradle_dependency:/root/.gradle/caches/modules-2/files-2.1
    working_dir: /tmp/Spring-Boot
    container_name: spring-boot
    depends_on:
      - spring-boot-reloader
    command: [ "bash", "./bootRun.sh" ]

  spring-boot-postgres:
    image: postgres:latest
    container_name: spring-boot-postgres
    environment:
      POSTGRES_PASSWORD: password
    depends_on:
      - spring-boot
    volumes:
      - /db/spring-boot-postgres:/var/lib/postgresql/data

  hapi-fhir:
    image: hapiproject/hapi:latest
    volumes:
      - ./HAPI-FHIR/jpaserver-starter:/data/hapi
    container_name: hapi-fhir
    environment:
     SPRING_CONFIG_LOCATION: file:///data/hapi/application.yaml

  hapi-fhir-postgres:
    image: postgres:latest
    container_name: hapi-fhir-postgres
    environment:
      POSTGRES_PASSWORD: password
    depends_on:
      - hapi-fhir
    volumes:
      - /db/hapi-fhir-postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 64550:8080
    depends_on:
      - spring-boot-postgres
      - hapi-fhir-postgres

  hardhat:
    build:
      context: ./Hardhat
      dockerfile: Dockerfile
    volumes:
      - ./Hardhat:/tmp/Hardhat
    working_dir: /tmp/Hardhat
    container_name: hardhat
    command: [ "bash", "./hardhatRun.sh" ]


  angular-server:
    build: 
      context: ./Angular
      dockerfile: Dockerfile
    volumes:
      - ./Angular:/tmp/Angular
    working_dir: /tmp/Angular
    container_name: angular-server
    command: [ "bash", "./AngularRun.sh" ]
  
  nginx:
    build: 
      context: ./Nginx
      dockerfile: Dockerfile
    volumes:
      - ./Nginx/conf.d:/etc/nginx/conf.d
      - ./Nginx/ssl:/etc/nginx/ssl
      - ./Nginx/error_page:/etc/nginx/html/error_page
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
      - angular-server
      - hardhat
      - adminer