version: '3.7'

services:
  spring-boot-reloader:
    build:
      context: ./Tiramisu_Spring_Boot
      dockerfile: Dockerfile
    volumes:
      - ./Tiramisu_Spring_Boot:/tmp/Tiramisu_Spring_Boot
    working_dir: /tmp/Tiramisu_Spring_Boot
    # restart: always
    container_name: spring-boot-reloader
    command: [ "bash", "./buildAndReload.sh" ]

  spring-boot:
    build:
      context: ./Tiramisu_Spring_Boot
      dockerfile: Dockerfile
    volumes:
      - ./Tiramisu_Spring_Boot:/tmp/Tiramisu_Spring_Boot
    working_dir: /tmp/Tiramisu_Spring_Boot
    container_name: spring-boot
    # restart: always
    command: [ "bash", "./bootRun.sh" ]
    ports:
      - 64510:8080
      - 35729:35729
      - 5005:5005

  hapi-fhir:
    image: "hapiproject/hapi:latest"
    volumes:
      - ./HAPI-FHIR/jpaserver-starter:/data/hapi
    container_name: hapi-fhir
    # restart: always
    environment:
     SPRING_CONFIG_LOCATION: file:///data/hapi/application.yaml
    ports:
      - 64511:8080

  # Comes from https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/docker-compose.yml
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    # case-sensitive, https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    # restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    depends_on:
      - hapi-fhir
    volumes:
      - ./HAPI-FHIR/mysql:/var/lib/mysql
    ports:
      - 64513:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hapi-fhir-mysql-phpMyAdmin
    # restart: always
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    depends_on:
      - hapi-fhir-mysql
    ports:
      - 64514:80

  hardhat:
    build:
      context: ./Hardhat
      dockerfile: Dockerfile
    volumes:
      - ./Hardhat:/tmp/Hardhat
    working_dir: /tmp/Hardhat
    container_name: hardhat
    # restart: always
    command: [ "bash", "./hardhatRun.sh" ]
    ports:
      - 64512:8545

  angular-server:
    build: 
      context: ./Angular
      dockerfile: Dockerfile
    volumes:
      - ./Angular:/tmp/Angular
    working_dir: /tmp/Angular
    container_name: angular-server
    # restart: always
    command: [ "bash", "./AngularRun.sh" ]
    ports:
     - 64500:4200

#  vs-code-server:
#    build:
#      context: ./VS_CODE_DEV_SERVER
#      dockerfile: Dockerfile
#    volumes:
#      # project's location
#      - ./:/home/coder/project
#      # setting's location
#      - ./.vscode-config:/root/.local/share/code-server/User
#      # gradle dependency location
#      - ./VS_CODE_DEV_SERVER/gradle_dependency:/root/.gradle/caches/modules-2/files-2.1
#    container_name: vs-code-server
#    environment:
#      - PASSWORD=1234 #optional
#      #- HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=1234 #optional
#      #- SUDO_PASSWORD_HASH= #optional
#    ports:
#      - 64550:8080