version: '3.7'

services:
  spring-boot-reloader:
    build:
      context: ./Tiramisu_Spring_Boot
      dockerfile: Dockerfile
    volumes:
      - ./:/tmp
    working_dir: /tmp
    container_name: spring-boot-reloader
    command: [ "./Tiramisu_Spring_Boot/buildAndReload.sh" ]

  spring-boot:
    build:
      context: ./Tiramisu_Spring_Boot
      dockerfile: Dockerfile
    volumes:
      - ./:/tmp
    working_dir: /tmp
    container_name: spring-boot
    command: [ "./Tiramisu_Spring_Boot/bootRun.sh" ]
    depends_on:
      - spring-boot-reloader
    ports:
      - 9000:8080
      - 35729:35729
      - 5005:5005

  hapi-fhir:
    image: "hapiproject/hapi:latest"
    volumes:
      - hapi-data:/data/hapi
    container_name: hapi-fhir
    configs:
      - source: hapi
        target: /data/hapi/application.yaml
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
    ports:
      - "9010:8080"

  vs-code-server:
    build:
      context: ./VS_CODE_DEV_SERVER
      dockerfile: Dockerfile
    volumes:
      # project's location
      - ./:/home/coder/project
      # setting's location
      - ./.vscode-config:/root/.local/share/code-server/User
    container_name: vs-code-server
    environment:
      - PASSWORD=1234 #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=1234 #optional
      #- SUDO_PASSWORD_HASH= #optional
      - http_proxy=127.0.0.1:5555
    ports:
      - 8090:8080
      - 5555:5555
