version: '3.7'

services:
  spring-boot-reloader:
    build:
      context: ./Spring-Boot
      dockerfile: Dockerfile
    volumes:
      - ./Spring-Boot:/tmp/Spring-Boot
      - /gradle_dependency:/root/.gradle/caches/modules-2/files-2.1
    working_dir: /tmp/Spring-Boot
    container_name: spring-boot-reloader
    command: [ "bash", "./buildAndReload.sh" ]

  spring-boot:
    build:
      context: ./Spring-Boot
      dockerfile: Dockerfile
    volumes:
      - ./Spring-Boot:/tmp/Spring-Boot
      - /gradle_dependency:/root/.gradle/caches/modules-2/files-2.1
    working_dir: /tmp/Spring-Boot
    container_name: spring-boot
    depends_on:
      - spring-boot-reloader
    command: [ "bash", "./bootRun.sh" ]

  # Comes from https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/docker-compose.yml
  spring-boot-mysql:
    image: mysql:latest
    container_name: spring-boot-mysql
    # case-sensitive, https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'spring'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    depends_on:
      - spring-boot
    volumes:
      - /db/spring-boot-mysql:/var/lib/mysql

  hapi-fhir:
    image: hapiproject/hapi:latest
    volumes:
      - ./HAPI-FHIR/jpaserver-starter:/data/hapi
    container_name: hapi-fhir
    environment:
     SPRING_CONFIG_LOCATION: file:///data/hapi/application.yaml

  # Comes from https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/docker-compose.yml
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    # case-sensitive, https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    depends_on:
      - hapi-fhir
    volumes:
      - /db/hapi-fhir-mysql:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpMyAdmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    depends_on:
      - hapi-fhir-mysql
      - spring-boot-mysql


  hardhat:
    build:
      context: ./Hardhat
      dockerfile: Dockerfile
    volumes:
      - ./Hardhat:/tmp/Hardhat
    working_dir: /tmp/Hardhat
    container_name: hardhat
    command: [ "bash", "./hardhatRun.sh" ]


  angular-server:
    build: 
      context: ./Angular
      dockerfile: Dockerfile
    volumes:
      - ./Angular:/tmp/Angular
    working_dir: /tmp/Angular
    container_name: angular-server
    command: [ "bash", "./AngularRun.sh" ]
  
  nginx:
    build: 
      context: ./Nginx
      dockerfile: Dockerfile
    volumes:
      - ./Nginx/conf.d:/etc/nginx/conf.d
      - ./Nginx/ssl:/etc/nginx/ssl
    container_name: nginx
    ports:
     - 80:80
     - 443:443
    depends_on:
      - angular-server
      - hardhat
      - phpmyadmin